apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-mini-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-mini
  template:
    metadata:
      labels:
        app: mlops-mini
    spec:
      containers:
      - name: mlops-mini
        image: mlops-mini:latest
        imagePullPolicy: Never

        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-mini-service
spec:
  selector:
    app: mlops-mini
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mlops-mini-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mlops-mini-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
